chore: 🤖 await dev server now takes port parameter

diff --git a/.scripts/await_dev_server b/.scripts/await_dev_server
--- a/.scripts/await_dev_server
+++ b/.scripts/await_dev_server
@@ -1,20 +1,16 @@
 #!/bin/bash
 
-# Parse env
-# This is generated by the `start_dev_server` script
-# which is assumed to start prior to executing this process
-source .tests/.env
+if [[ -z "$1" ]]; then
+  echo "👹 Oops! Missing port number."
+  exit 1
+fi
 
 max_count=10
 count=0
 timeout=15
-dev_server_url="http://localhost:$NEXT_DEV_SERVER_PORT"
+dev_server_url="http://localhost:$1"
 http_success_status="HTTP/1.1 200 OK"
 
-if [[ -z "$NEXT_DEV_SERVER_PORT" ]]; then
-  echo "👹 Oops! Missing port number."
-  exit 1
-fi
 
 echo "🤖 Await for development server at $dev_server_url"
 
