chore: 🤖 run tests script should call await dev server firstly

diff --git a/.scripts/await_dev_server b/.scripts/await_dev_server
--- a/.scripts/await_dev_server
+++ b/.scripts/await_dev_server
@@ -1,19 +1,24 @@
 #!/bin/bash
 
+# Parse env
+# This is generated by the `start_dev_server` script
+# which is assumed to start prior to executing this process
+source .tests/.env
+
 max_count=10
 count=0
 timeout=15
-port=$1
-dev_server_url="http://localhost:$port"
+dev_server_url="http://localhost:$NEXT_DEV_SERVER_PORT"
+http_success_status="HTTP/1.1 200 OK"
 
-if [[ -z "$1" ]]; then
-  echo "👹 Oops! Missing port number. When calling the script make sure you pass the port number as an argument."
+if [[ -z "$NEXT_DEV_SERVER_PORT" ]]; then
+  echo "👹 Oops! Missing port number."
   exit 1
 fi
 
 echo "🤖 Await for development server at $dev_server_url"
 
-while ! curl -s "$dev_server_url" > /dev/null; do
+while ! curl -sfLI "$dev_server_url" | grep -q "$http_success_status"; do
   if [[ $count -ge $max_count ]]; then
     echo "👹 Oops! The dev server failed to start after $max_count for some reason..."
     exit 1
