chore: 🤖 pass env var for base path

diff --git a/.scripts/put_build_in_base_path b/.scripts/put_build_in_base_path
--- a/.scripts/put_build_in_base_path
+++ b/.scripts/put_build_in_base_path
@@ -2,6 +2,12 @@
 
 set -e
 
+if [[ -z "$1" ]]; then
+  echo "👹 Oops! Missing arguments required for base path NEXT_PUBLIC_BASE_PATH"
+  exit 1
+fi
+
+NEXT_PUBLIC_BASE_PATH="$1"
 OUTPUT_DIR="out"
 TEMP_DIR="$OUTPUT_DIR.bak"
 DEST_DIR="$OUTPUT_DIR/$NEXT_PUBLIC_BASE_PATH"
@@ -19,11 +25,16 @@ mkdir -p "$DEST_DIR" || exit 1
 echo "✅ Created $DEST_DIR"
 
 cp -r "$TEMP_DIR/" "$DEST_DIR"
-echo "✅ Copied files from $TEMP_DIR to $DEST_DIR"
+echo "✅ Moved files from $TEMP_DIR to $DEST_DIR"
+
+rm -rf "$TEMP_DIR" || exit 1
+echo "✅ Removed $TEMP_DIR"
 
 if [[ -d "$DEST_DIR" && "$(ls -A $DEST_DIR)" ]]; then
   echo "✅ Created $DEST_DIR"
 else
   echo "👹 Oops! Failed to create $DEST_DIR for some reason..."
+
   exit 1
 fi
+
