fix: 🐛 TIAS use force push with lease

diff --git a/.github/workflows/changeset-version-management.yml b/.github/workflows/changeset-version-management.yml
--- a/.github/workflows/changeset-version-management.yml
+++ b/.github/workflows/changeset-version-management.yml
@@ -20,10 +20,6 @@ jobs:
         with:
           app-id: ${{ secrets.FLEEK_PLATFORM_BOT_APP_ID }}
           private-key: ${{ secrets.FLEEK_PLATFORM_BOT_PRIVATE_KEY }}
-          permissions:
-            contents: write
-            checks: write
-            pull-requests: write
 
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -99,6 +95,8 @@ jobs:
 
       - name: Commit changes
         if: ${{ steps.changeset-status.outputs.skip != 'true' }}
+        env:
+          BRANCH_NAME: ${{ github.ref_name }}
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
@@ -121,8 +119,10 @@ jobs:
 
           echo "✅ Committed package version!"
 
-          if ! git push; then
-            echo "👹 Oops! Failed to push changes."
+          # Using force push, due to issue bypassing
+          # branching protection rules
+          if ! git push --force-with-lease origin "$BRANCH_NAME"; then
+            echo "👹 Oops! Failed to push changes to $BRANCH_NAME"
             exit 1
           fi
 
