chore: 🤖 re-enable test hash verification

diff --git a/.github/workflows/test-runner.yml b/.github/workflows/test-runner.yml
--- a/.github/workflows/test-runner.yml
+++ b/.github/workflows/test-runner.yml
@@ -45,32 +45,32 @@ jobs:
       # generated after a succesful test
       # We can use this information to prevent
       # executing test runs for unchanged source
-      # - name: Check for test run hash
-      #   id: has_test_run_hash
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   run: |
-      #     ghToken="$GITHUB_TOKEN"
-      #     orgRepo="fleek-platform/dashboard"
-      #     targetArtifactFilename="test_run_hash"
+      - name: check for test run hash
+        id: has_test_run_hash
+        env:
+          github_token: ${{ secrets.github_token }}
+        run: |
+          ghtoken="$github_token"
+          orgrepo="fleek-platform/dashboard"
+          targetartifactfilename="test_run_hash"
 
-      #     if ! .scripts/download_artifact "$ghToken" "$orgRepo" "$targetArtifactFilename"; then
-      #       echo "👹 Oops! Failed to download artifact $targetArtifactFilename"
-      #       exit 1
-      #     fi
+          if ! .scripts/download_artifact "$ghtoken" "$orgrepo" "$targetartifactfilename"; then
+            echo "👹 oops! failed to download artifact $targetartifactfilename"
+            exit 1
+          fi
 
-      #     source .scripts/test_runner_vars
-      #     current_hash=$(.scripts/hash_dir "$csv_paths")
-      #     expected="[TEST_RUN] $current_hash"
-      #     artifact_content=$(cat "$targetArtifactFilename")
+          source .scripts/test_runner_vars
+          current_hash=$(.scripts/hash_dir "$csv_paths")
+          expected="[test_run] $current_hash"
+          artifact_content=$(cat "$targetartifactfilename")
 
-      #     if [[ "$artifact_content" = "$expected" ]]; then
-      #       echo "match=true" >> "$GITHUB_OUTPUT"
-      #       echo "✅ Found a test run hash"
-      #     else
-      #       echo "match=false" >> "$GITHUB_OUTPUT"
-      #       echo "⚠️A test run hash wasn't found"
-      #     fi
+          if [[ "$artifact_content" = "$expected" ]]; then
+            echo "match=true" >> "$github_output"
+            echo "✅ found a test run hash"
+          else
+            echo "match=false" >> "$github_output"
+            echo "⚠️a test run hash wasn't found"
+          fi
 
       # It checks if a test has already run
       # for the current source state
@@ -205,3 +205,5 @@ jobs:
         with:
           name: test_run_hash
           path: test_run_hash
+          retention-days: 90
+
